//config
export const SET_LOCATION = "SET_LOCATION";
export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";
export const AUTHENTICATE = "AUTHENTICATE";
export const LOGOUT = "LOGOUT";
export const UPDATE_CONFIG_DATA = "UPDATE_CONFIG_DATA";
export const SET_BACK_URL = "SET_BACK_URL";
export const SET_CUR_SERVICE = "SET_CUR_SERVICE";

//cart
export const SET_QUANTITY = "SET_QUANTITY";
export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const SET_CHECKOUT_DATA = "SET_CHECKOUT_DATA";
export const CLEAR_AND_ADD = "CLEAR_AND_ADD";
export const CLEAR_CART = "CLEAR_CART";

//test
export const LOAD_DATA = "LOAD_DATA";

//product
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const SET_CUR_PRODUCT = "SET_CUR_PRODUCT";

//restaurant
export const SET_CUR_RESTAURANT = "SET_CUR_RESTAURANT";
export const UPDATE_RESTAURANTS = "UPDATE_RESTAURANTS";
export const SET_LOADED_RESTAURANTS = "SET_LOADED_RESTAURANTS";
export const SET_RELOAD_RESTAURANTS = "SET_RELOAD_RESTAURANTS";

//address
export const SET_CUR_ADDRESS = "SET_CUR_ADDRESS";
export const SET_DEFAULT_ADDRESS = "SET_DEFAULT_ADDRESS";
export const ADD_NEW_ADDRESS = "ADD_NEW_ADDRESS";
export const SET_ADDRESS_LIST = "SET_ADDRESS_LIST";

//orders
export const ADD_NEW_ORDER = "ADD_NEW_ORDER";
export const CLEAR_ORDERS = "CLEAR_ORDERS";
export const SET_ALL_ORDERS = "SET_ALL_ORDERS";
export const SET_ORDER_STATUS = "SET_ORDER_STATUS";
export const SET_ACTIVE_ORDERS = "SET_ACTIVE_ORDERS";

//notifications
export const SET_LOADED_NOTIFICATIONS = "SET_LOADED_NOTIFICATIONS";
export const SET_RELOAD_NOTIFICATIONS = "SET_RELOAD_NOTIFICATIONS";